# Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
COVER_MESSAGE_SENDING_INTERVAL: 10s 
APPLICATION_MESSAGE_RECEIVING_INTERVAL: 15s 
PUBLISH_JOB_FAILED_TIMEOUT: 1m
PUBLISH_JOB_CHECKING_INTERVAL: 30s 
TCP_REQUEST_TIMEOUT: 10s 
MAINTAIN_PATHS_HEALTH_CHECKING_INTERVAL: 1m
PUBLISH_CONDITION_CHECKING_INTERVAL: 1m
FULFILL_PUBLISH_CONDITION_TIMEOUT: 5m
FULFILL_PUBLISH_CONDITION_INTERVAL: 1m

HALF_OPEN_PATH_BUFFER_SIZE: 10000
TARGET_NUMBER_OF_CONNECTED_PATHS: 0
MAXIMUM_NUMBER_OF_COVER_NODES: 15
NUMBER_OF_COVER_NODES_FOR_PUBLISH: 0
MOVE_UP_REQUIREMENT_FAILURE_THRESHOLD: 3

TCP_SERVER_LISTEN_PORT: ":5001"
HTTP_SERVER_LISTEN_PORT: ":5000"
NODE_DISCOVERY_SERVER_LISTEN_PORT: ":5200"
IMMUTABLE_STORAGE_SERVER_LISTEN_PORT: ":5100"

TESTING_FLAG: true
NODE_ALIAS: N3

