# Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
COVER_MESSAGE_SENDING_INTERVAL: 10s 
APPLICATION_MESSAGE_RECEIVING_INTERVAL: 15s 
PUBLISH_JOB_FAILED_TIMEOUT: 10m
PUBLISH_JOB_CHECKING_INTERVAL: 30s 
TCP_REQUEST_TIMEOUT: 10s 
MAINTAIN_PATHS_HEALTH_CHECKING_INTERVAL: 1m
PUBLISH_CONDITION_CHECKING_INTERVAL: 1m
FULFILL_PUBLISH_CONDITION_TIMEOUT: 5m
FULFILL_PUBLISH_CONDITION_INTERVAL: 10s

HALF_OPEN_PATH_BUFFER_SIZE: 5000
TARGET_NUMBER_OF_CONNECTED_PATHS: 1
MAXIMUM_NUMBER_OF_COVER_NODES: 15
NUMBER_OF_COVER_NODES_FOR_PUBLISH: 2
MOVE_UP_REQUIREMENT_FAILURE_THRESHOLD: 3

# Controls where the HTTP server will listen on
# To Bind all IP, set HTTP_SERVER_LISTEN_IP as ""
# PS, in general it is not recommended to do so, as other network participants are not supposed to have access on your HTTP server.
HTTP_SERVER_LISTEN_IP: "127.0.0.2"
HTTP_SERVER_LISTEN_PORT: ":3000"

# Point to the address that the Immutable Storage gRPC Server is running
IMMUTABLE_STORAGE_SERVER_LISTEN_IP: "127.0.0.2"
IMMUTABLE_STORAGE_SERVER_LISTEN_PORT: ":3100"

# Point to the address that the Node Discovery gRPC Server is running
NODE_DISCOVERY_SERVER_LISTEN_IP: "127.0.0.2"
NODE_DISCOVERY_SERVER_LISTEN_PORT: ":3200"

# Uncomment it when you wish the node to join cluster at this contact node during initialization
# CLUSTER_CONTACT_NODE_IP: "127.0.0.1"

# Params for testing:

# TCP Server by default should bind to all IP 
# Defining TESTING_TCP_SERVER_LISTEN_IP may cause it to be undiscoverable by other nodes on the internet
TESTING_TCP_SERVER_LISTEN_IP: "127.0.0.2"
NODE_ALIAS: Cover