# Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
COVER_MESSAGE_SENDING_INTERVAL: 10s 
APPLICATION_MESSAGE_RECEIVING_INTERVAL: 15s 
PUBLISH_JOB_FAILED_TIMEOUT: 10m
PUBLISH_JOB_CHECKING_INTERVAL: 30s 
TCP_REQUEST_TIMEOUT: 10s 
MAINTAIN_PATHS_HEALTH_CHECKING_INTERVAL: 60s
PUBLISH_CONDITION_CHECKING_INTERVAL: 1m
FULFILL_PUBLISH_CONDITION_TIMEOUT: 5m
FULFILL_PUBLISH_CONDITION_INTERVAL: 10s

HALF_OPEN_PATH_BUFFER_SIZE: 10000
TARGET_NUMBER_OF_CONNECTED_PATHS: 3
MAXIMUM_NUMBER_OF_COVER_NODES: 15
NUMBER_OF_COVER_NODES_FOR_PUBLISH: 2
MOVE_UP_REQUIREMENT_FAILURE_THRESHOLD: 3

TCP_SERVER_LISTEN_PORT: ":3001"
HTTP_SERVER_LISTEN_PORT: ":3000"
NODE_DISCOVERY_SERVER_LISTEN_PORT: ":3200"
IMMUTABLE_STORAGE_SERVER_LISTEN_PORT: ":3100"

TESTING_FLAG: true